defaults:
  - _self_
  - data: default
  - model: default
  - train: default
  - sweep: none

hydra:
  run:
    dir: outputs/${now:%Y%m%d_%H%M}
  sweep:
    dir: multirun/${now:%Y%m%d_%H%M}
    subdir: beta=${train.beta}_gamma=${train.gamma}
